version: '3.4'
services:
  springboot-app:
    ports:
      - 8080:8080
    container_name: springboot-app
    build:
      context: ./SpringBoot-Backend
      args:
        JAR_FILE: /springboot-cassandra.jar
    restart: always

  cassandradb:
    image: cassandra
    container_name: cassandradb
    ports:
      - "9042:9042"

  employees-ui:
    build: ./Angular-Frontend
    container_name: employees-ui
    ports:
      - 4200:80
